### ISSUE TITLE
Plugin stopped to work after update Flutter engine

### ISSUE THREAD

**Issue by felipecs81** [v3rm0n/intercom_flutter#173]
The plugin was working fine but after update Flutter to the new version today, the Intercom stopped to work.

This is the error when the app is launched:

<img width="610" alt="Screen Shot 2021-10-21 at 1 13 02 pm" src="https://user-images.githubusercontent.com/36759033/138215508-c986eaa2-0d68-4fb2-9d5d-dbfec8c1d3a2.png">

Then when I try to launch the Intercom, nothing happens.

Platform: Web

Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (6 days ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4

environment:
  sdk: '>=2.14.0 <3.0.0'

intercom_flutter: ^5.0.2

Thank you.

**Comment by deepak786** [comment]
@felipecs81 
I will check the issue.

Thanks.

**Comment by deepak786** [comment]
the issue is resolved and the new intercom_flutter version 5.0.3 is uploaded.

```
intercom_flutter: 5.0.3
```

If you like the work, Don't hesitate to buy me a coffee.
<a href="https://www.buymeacoffee.com/deepakdroid" target="_blank"><img src="https://cdn.buymeacoffee.com/buttons/v2/default-yellow.png" alt="Buy Me A Coffee" width="150px"></a>

**Comment by mattkj** [comment]
Updated Flutter to latest stable, updated intercom_flutter to 5.0.3 and ran flutter clean.

Still getting the error.

**Comment by deepak786** [comment]
@mattkj 

Could you please share the sample with reproducible issue?
The intercom flutter example is working fine.

@ffelipecs81 is the issue solved for you?

**Comment by deepak786** [comment]
I have reported the issue to the Intercom support team.
You guys can also report the same issue to Intercom support.

**Comment by deepak786** [comment]
I received an update from the Intercom support team that the issue is solved.

![Screen Shot 2021-10-22 at 9 00 18 PM](https://user-images.githubusercontent.com/14223997/138482298-d064a649-8ac8-4515-874a-0f442978f293.png)


@mattkj please check.

**Comment by mattkj** [comment]
@deepak786 Error is gone now 👍 . Thanks!
