### ISSUE TITLE
Failed to register a device token - identity verification is not setup correctly

### ISSUE THREAD

**Issue by adamkoch** [v3rm0n/intercom_flutter#578]
Related: #562 

Firebase Crashlytics is reporting the following crash in my app ever since upgrading `intercom_flutter`. Note that there was no code changed relating to Intercom or push tokens, it was all working with zero crashes before, crashes started after upgrading.

```
Non-fatal Exception: FlutterError
PlatformException(4003, ERROR - Failed to register a device token - identity verification is not setup correctly, {errorMessage: ERROR - Failed to register a device token - identity verification is not setup correctly, errorCode: 4003}, null)
0  ???                            0x0 StandardMethodCodec.decodeEnvelope + 653 (message_codecs.dart:653)
1  ???                            0x0 MethodChannel._invokeMethod + 367 (platform_channel.dart:367)
2  ???                            0x0 MethodChannelIntercomFlutter.sendTokenToIntercom + 175 (method_channel_intercom_flutter.dart:175)
```

My app version vs `intercom_flutter` version:

No crashes in my app equal or prior to this version:
```
my app version:  1.3.68
intercom_flutter: ^9.4.7
```

Crashes started from this version onward:
```
my app version: 1.3.69
intercom_flutter: ^9.4.10
```

Here is the crashlytics report:
<img width="1184" height="417" alt="Image" src="https://github.com/user-attachments/assets/9af73137-e62b-449d-a5c7-e5d77222fa60" />

Other things worth noting:
 - Crashes are iOS only
 - Crashlytics reports 99% crashes happen in background
 - I still use legacy HMAC Intercom identify verification
 - I cannot reproduce this myself and it does not seem to be all iOS users, only a small percentage

I did try and mitigate the crashes by adding the following code before getting/sending the token to Intercom, however it has not stopped the crashes:
```
  Future<bool> get isNotificationEnabled async {
    if (kIsWeb || kDebugMode) {
      return false;
    }

    try {
      final settings = await _firebaseMessaging.getNotificationSettings();
      return settings.authorizationStatus == AuthorizationStatus.authorized ||
          settings.authorizationStatus == AuthorizationStatus.provisional;
    } catch (e) {
      log('PushNotification.isNotificationEnabled error: $e');
      return false;
    }
  }
```

**Comment by adamkoch** [comment]
90 day crashlytics graph:

<img width="617" height="361" alt="Image" src="https://github.com/user-attachments/assets/7803b5bb-19c0-48c0-869c-5974363ac66a" />

**Comment by deepak786** [comment]
@adamkoch Which error do you have?

```
PlatformException(4001, ERROR - Failed to register a device token - push notifications are not enabled on the host device, {errorMessage: ERROR - Failed to register a device token - push notifications are not enabled on the host device, errorCode: 4001}, null)
```

or

```
PlatformException(4003, ERROR - Failed to register a device token - identity verification is not setup correctly, {errorMessage: ERROR - Failed to register a device token - identity verification is not setup correctly, errorCode: 4003}, null)
```

Because in the previous issue, you commented the different issue but here it is different.

**Comment by adamkoch** [comment]
@deepak786 - oh dear, so sorry! my mistake. Crashlytics has collapsed the two errors into a single item and I didn't even notice 🙈

So the older logs were 4001, but those actually went away (I guess after one of the further intercom_flutter version upgrades?). Now all the errors are 4003.

So I guess more related to HMAC vs JWT? Did I miss something I needed to do to keep HMAC working?

**Comment by deepak786** [comment]
This issue was fixed in `intercom_flutter: 9.4.9` which uses [intercom-ios 19.2.1](https://github.com/intercom/intercom-ios/releases/tag/19.2.1)

But you said you have this issue from `intercom_flutter: 9.4.10`. So I suggest try the following version:
- `intercom_flutter: 9.4.12`
- `intercom_flutter: 9.4.13`
- `intercom_flutter: 9.4.14`
- `intercom_flutter: 9.4.17`
- `intercom_flutter: 9.4.18`

because in these versions, Intercom iOS sdk version is updated.

If the issue is still not resolved, please contact Intercom support.

**Comment by deepak786** [comment]
But as per this comment https://github.com/v3rm0n/intercom_flutter/issues/562#issuecomment-3549028440

The issue is present in the latest versions also `intercom_flutter: 9.4.16`.
So I suggest to report the issue directly to Intercom support.

**Comment by adamkoch** [comment]
I forgot to include my current config which is:

```
my app version:  1.3.75
intercom_flutter: ^9.4.16
```

And I still receive the crashes as per crashlytics screenshots above.

I have a test version rolling out now that switches to JWT instead which I'm hoping will fix it.

**Comment by Dara-Kelly-59** [comment]
Hey @adamkoch. Could I get some more information from you about this?

- Please provide a minimal Flutter code example showing the exact sequence: when setUserHash is called, when device token registration is attempted, and the app state transitions (foreground → background) that trigger the crash.

- Clarify whether crashes occur on both WiFi and cellular networks or are network-specific, and confirm push notification certificate configuration is correctly set up in both Firebase and Intercom consoles.

- Extract and include specific iOS OS versions from Crashlytics reports (minimum and maximum versions affected). Background execution and identity verification handling differ significantly between iOS versions and are central to this bug.

- Include device models from crash reports (e.g., iPhone 14, iPhone 15, etc.) to determine if the issue correlates with specific hardware or iOS versions.

**Comment by adamkoch** [comment]
Sure, no prob.

First of all, I put out a new release which updates `intercom_flutter` from `9.4.16` -> `9.4.18` and also moves from HMAC to JWT. While the number of crash reports seems to have continued to decrease (not sure why), I still do see the crash on this version of my app.

> Please provide a minimal Flutter code example showing the exact sequence: when setUserHash is called, when device token registration is attempted, and the app state transitions (foreground → background) that trigger the crash.

Well I can't reproduce it myself, it all works fine when I test locally or on my devices. But my Intercom code is basically 3 functions
 - Initialize runs on app startup
 - `setUser()` runs once the user object is populated and sets JWT (previously HMAC)
 - `updatePushTokens()` runs after `setUser()` once user is populated and after tokens are fetched

However, looking at the code, I do some potential race conditions where user/jwt and push tokens may not get strictly called in sequence. Although the push tokens code always checks to make sure the tokens are available first (which they aren't if user has not been set). But potentially this could be the problem? As per original report, I never had an issue until recent intercom_flutter versions so maybe something changed?

```
Future<void> initialize() => Intercom.instance.initialize(
    intercomAppId,
    iosApiKey: intercomIosApiKey,
    androidApiKey: intercomAndroidApiKey,
);

void setUser(User user) async {
  if (email != null && email.isNotEmpty) {
    final jwt = await _fetchIntercomJwt();
    if (jwt != null) {
      await Intercom.instance.setUserJwt(jwt);
      await Intercom.instance.loginIdentifiedUser(userId: user.uid);
    }
  }
}

void updatePushTokens({String? fcmToken, String? apnsToken}) {
  if (defaultTargetPlatform == TargetPlatform.android && fcmToken != null) {
      Intercom.instance.sendTokenToIntercom(fcmToken);
  } else if (defaultTargetPlatform == TargetPlatform.iOS && apnsToken != null) {
      Intercom.instance.sendTokenToIntercom(apnsToken);
    }
}
```

> Clarify whether crashes occur on both WiFi and cellular networks or are network-specific, and confirm push notification certificate configuration is correctly set up in both Firebase and Intercom consoles.

I don't know, crashlytics doesn't seem to have if it's WiFi or cellular. But push notifications seem to be set up fine to me - I have been using the same certs/setup for over 2 years and never had problems until this came up. I also test myself on an Android and iOS device and the push messages all arrive fine when I test.

>Extract and include specific iOS OS versions from Crashlytics reports (minimum and maximum versions affected). Background execution and identity verification handling differ significantly between iOS versions and are central to this bug.

OS versions:
<img width="568" height="367" alt="Image" src="https://github.com/user-attachments/assets/70df3a30-94bd-41b9-bc66-79d58fe45acc" />

Devices are 84% iPhone, 16% iPad. iPhone breakdown:
<img width="557" height="500" alt="Image" src="https://github.com/user-attachments/assets/c3bd9be2-2a0a-444e-aac8-d4db23023ab9" />

Devices states is 100% background crash now:
<img width="556" height="340" alt="Image" src="https://github.com/user-attachments/assets/3f6a89d0-696a-476b-9d97-98db148629c3" />

**Comment by Dara-Kelly-59** [comment]
Thank you! I'll pass this info on to our dev team!

**Comment by cerealexx** [comment]
@Dara-Kelly-59 is happening in our app too. We've been always fine with hmac, but iOS is totally broken since. 
Is JWT identification mandatory now?

**Comment by Dara-Kelly-59** [comment]
@cerealexx JWT identification is not mandatory but it is recommended.

**Comment by Dara-Kelly-59** [comment]
@adamkoch 

Hey Adam, I've heard back from our dev team.

Just to clarify the version side of things: in iOS SDK 19.2.1 we fixed a bug where, if identity verification was enabled and you were using JWT, device token registration would basically always fail with 4003. From 19.2.1 onwards, JWT is treated correctly for device token registration, the same as HMAC.

What you’re seeing now looks different. My current thinking is that these remaining 4003s are mostly timing‑related. The SDK will only submit the device token once config has been fetched, and either identity verification is off, or there’s a valid HMAC/JWT set for the current user.

If sendTokenToIntercom runs before that’s true, we return 4003 instead of sending the token.

On our side, we can definitely improve this by making the behaviour around “not ready yet” state clearer and more forgiving.

My guess would be that you are seeing these 4003s  because you are are calling sendTokenToIntercom while the app is in the background, before config has been fetched and identity verification has been fully set up for that user.Please confirm whether this is the case or not.

**Comment by adamkoch** [comment]
Thanks for the update @Dara-Kelly-59. I think that summary sounds fairly likely and reasonable. I will go back and see if I can make sure `sendTokenToIntercom()` never runs before `setUserJwt()` and see if that fixes it. I will report back here but it may be a few weeks before we get a new build out.

I think the two mysteries are:

 - why only in the background? our app generally doesn't run in the background and is always a logged-in experience. it does the intercom init (jwt and push tokens) upon user being logged-in (at app startup). so while there may exist a race condition on app startup, why would that issue surface only when the app is in the background?
 - prior to intercom_flutter ^9.4.7, we never saw these issues at all. perhaps some code was refactored inside intercom flutter during the jwt refactor that made it start showing up though

**Comment by Dara-Kelly-59** [comment]
No worries @adamkoch!

The background-only pattern makes sense with how the SDK gates token upload.

The SDK only submits the device token after config is fetched and either messenger security is off or a valid JWT/HMAC has been set for the current user. If sendTokenToIntercom is called before that, it returns 4003 (“identity verification not set up yet”) rather than uploading the token. This can surface when the app is started or resumed in the background and your code races to send the token before setUserJwt/setUserHash has run.

The fix is to ensure setUserJwt (or setUserHash if you’re still on HMAC) runs before any Intercom calls and to gate sendTokenToIntercom so it only runs after the user session is established and the app is foregrounded. In Flutter terms: call setUserJwt, then login the user, and only after the login promise resolves and the app lifecycle is resumed, call sendTokenToIntercom. If your app sometimes launches in the background (e.g., token refresh), skip sending until foreground.

Re the version note: the iOS SDK bug where JWT-based token registration always failed with 4003 was fixed in 19.2.1; upgrading surfaced “real” timing issues that older versions either masked or handled differently. That’s why you didn’t see it pre ^9.4.7 but do now, your plugin likely picked up new iOS SDK behavior and you’re now hitting the timing window. The ordering/guard above should resolve it.

**Comment by adamkoch** [comment]
Thanks for the super detailed response @Dara-Kelly-59! 🙇  That's really helpful and I think explains just about everything I've noticed.

I have a release rolling out to production as of today that attempts to fix things based on everything discussed. Will report back in a few more days to see if it's all resolved.

**Comment by adamkoch** [comment]
No crashes since Monday in the release with the fix. I think it's fixed 😁

For others - the fix was exactly as @Dara-Kelly-59 wrote above - I made sure that `setUserJwt()` always ran prior to `sendTokenToIntercom()`.

Thanks for all the help!
